[project]
name = "soc-ingame-feedback"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "cozepy>=0.16.1",
    "fastapi>=0.115.12",
    "jinja2>=3.1.6",
    "uvicorn>=0.34.2",
]
